services:

    Networking\InitCmsBundle\Menu\FrontendMenuBuilder:
        autowire: true
        $allowLocaleCookies: '%networking_init_cms.allow_locale_cookie%'

    # Create the left main menu and right main menu for the frontend
    sandbox_init_cms.menu.frontend_main_menu_left:
        class: Knp\Menu\MenuItem
        factory: 'Networking\InitCmsBundle\Menu\FrontendMenuBuilder:createMainMenu'
        arguments: [menu_name: 'Main menu', 'nav nav-tabs nav-main' ]
        tags:
            - { name: knp_menu.menu, alias: mainMenu }

    sandbox_init_cms.menu.frontend_main_menu_language:
        class: Knp\Menu\MenuItem
        factory: 'Networking\InitCmsBundle\Menu\FrontendMenuBuilder:createFrontendLangMenu'
        arguments: [ '@request_stack', '%networking_init_cms.page.languages%', 'nav nav-pills pull-right' ]
        tags:
            - { name: knp_menu.menu, alias: langMenu }


    # Create the side menu for the frontend
    sandbox_init_cms.menu.frontend_sub_menu:
        class: Knp\Menu\MenuItem
        factory: 'Networking\InitCmsBundle\Menu\FrontendMenuBuilder:createSubnavMenu'
        arguments: [ 'Main menu', 'nav nav-pills']
        tags:
            - { name: knp_menu.menu, alias: subMenu }



    sandbox_init_cms.menu.frontend_footer_menu:
        class: Knp\Menu\MenuItem
        factory: 'Networking\InitCmsBundle\Menu\FrontendMenuBuilder:createFooterMenu'
        arguments: ['Footer menu', 'nav nav-pills']
        tags:
            - { name: knp_menu.menu, alias: footerMenu }

