# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
parameters:
    fos_elastica.use_v5_api: true

fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            index_name: 'sandbox'
            client: default
            finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            my_search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, deu_snowball]
                            deu_snowball:
                                type: snowball
                                language: German2
                        filter:
                            deu_snowball:
                                type: snowball
                                language: German2

            types:
                page:
                    properties:
                        name: {type: 'string',analyzer: my_search_analyzer}
                        metaTitle:  {type: 'string',analyzer: my_search_analyzer}
                        locale: { type: 'string', store: false}
                        content: {type: 'string',analyzer: my_search_analyzer}
                        url: {type: 'string',"index": "no"}
                    persistence:
                        identifier: resourceId
                        model: Networking\InitCmsBundle\Entity\PageSnapshot
                        model_to_elastica_transformer:
                            service: 'Networking\ElasticSearchBundle\Transformer\PageSnapshotToElasticaTransformer'
                media:
                    #                    indexable_callback: [ 'Networking\ElasticSearchBundle\Transformer\IndexableChecker', 'isIndexable' ]
                    properties:
                        name: {type: 'string',analyzer: my_search_analyzer}
                        metaTitle:  {type: 'string',analyzer: my_search_analyzer}
                        locale: { type: 'string', store: false}
                        content: {type: 'string',analyzer: my_search_analyzer}
                        url: {type: 'string',"index": "no"}
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model: Networking\InitCmsBundle\Entity\Media
                        model_to_elastica_transformer:
                            service: 'Networking\ElasticSearchBundle\Transformer\MediaToElasticaTransformer'
