imports:
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/mopa_bootstrap.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_block.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_doctrine_admin.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_formatter.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_user.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/symfony_cmf_routing_extra.yaml" }

networking_init_cms:
    # Set a cookie in the fronted end for language. If disabled, the URL will be prefixed with the locale
    allow_locale_cookie: true

    # Simple php based cache for caching the rendered HTML in the frontend
    cache:
        activate: true #default false
        cache_time: 86400 #default value
        cache_service_class: 'Networking\InitCmsBundle\Lib\PhpCache' #default value

    # Show admin toolbar when in the frontend
    admin_toolbar:
        toolbar: true #Default is activated
        position: 'top' #Choices are 'top' or 'bottom'
    translation_fallback_route: 'initcms_404' #Default fallback to 404 page
    no_translation_template: '@NetworkingInitCms/no_translation_found.html.twig' #
    404_template: '@NetworkingInitCms/error_404.html.twig' #Fallback to a 404 page included
    # Tag tree for use in the media manager
    show_tag_tree: true #Default is true
    multiple_media_tags: true #Default is true

    # Language set up, label is used in the default frontend language switcher menu
    languages:
        - {label: 'Deutsch', locale: 'de'}
        - {label: 'English', locale: 'en'}

    # Add content types here
    content_types:
        - { name: 'Text' , class: 'Networking\InitCmsBundle\Entity\Text'}
        - { name: 'Gallery Viewer' , class: 'Networking\InitCmsBundle\Entity\GalleryView'}

    # Classes to be used for the page and user entities
    class:
        page: "App\\Entity\\Page"
        user: "App\\Entity\\User"

    # Default template settings to get you started
    templates:
        'app_single_column':
            template: "page/one_column.html.twig"
            name: "Single Column"
            icon: "build/img/template_header_one_column.png"
            zones:
                - { name: header, class: 'col-md-12' }
                - { name: main_content, class: 'col-md-12'}
        'app_two_column':
            template: "page/two_column.html.twig"
            name: "Two Column"
            icon: "build/img/template_header_two_column.png"
            zones:
                - { name: header , class: 'col-md-12'}
                - { name: left , class: 'col-md-3'}
                - { name: right , class: 'col-md-9'}
