oneup_uploader:
    mappings:
        media_admin:
            frontend: custom
            custom_frontend:
                class: "Networking\\InitCmsBundle\\Controller\\OneUploader\\MediaMultiUploadController"
                name: "mediaAdminMultiUploader"