twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
#    form_themes:
#        - 'Form/form_div.html.twig'
    number_format:
        decimals: 2
        decimal_point: '.'
        thousands_separator: ' '
