language: php

# Allows use container-based infrastructure
sudo: false


# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2

before_script:
  - curl -sSfL -o ~/.phpenv/versions/7.2/bin/phpunit https://phar.phpunit.de/phpunit-7.phar

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini
  - php -i | grep memory_limit


# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install --no-interaction --prefer-dist
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load --fixtures="tests/Fixtures" -n --env=test


script: phpunit  --verbose -c app/phpunit.xml
