language: php

# Allows use container-based infrastructure
sudo: false


# Cache composer packages so "composer install" is faster
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

php:
  - 7.2

before_install:
  - phpenv config-add travis.php.ini
  - phpenv config-rm xdebug.ini
#  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
#  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;



# Install composer dependencies,
# Create database, schema and fixtures
install:
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - composer update --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load --fixtures="tests/Fixtures" -n --env=test
  - yarn install
  - yarn encore dev


env:
  global:
    - PHPUNIT_FLAGS="-v --debug"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - STABILITY="dev"
    - SYMFONY_DEPRECATIONS_HELPER="weak"
    - APP_ENV=test
    - LOCALE=en


script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS