language: php

# Allows use container-based infrastructure
sudo: false


# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

php:
  - 7.2

before_install:
  - phpenv config-add travis.php.ini
  - php -i | grep memory_limit
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;



# Install composer dependencies,
# Create database, schema and fixtures
install:
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
  - composer update --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load --fixtures="tests/Fixtures" -n --env=test


env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - STABILITY="dev"
    - SYMFONY_DEPRECATIONS_HELPER="weak_vendors"


script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS