language: php

# Allows use container-based infrastructure
sudo: false


# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini


# Install composer dependencies,
# Create database, schema and fixtures
install:
  - travis_retry composer update --no-interaction --prefer-dist
  - cp app/config/parameters.yml.test app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load --fixtures="src/Application/Networking/InitCmsBundle/Tests/Fixtures" -n --env=test


script: phpunit  --verbose -c app/phpunit.xml
