NetworkingInitCmsBundle:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing/routing.yml"
    prefix:   /

networking_form_generator:
    resource: "@NetworkingFormGeneratorBundle/Resources/config/routing.yml"
    prefix:   /

#networking_elastic_search:
#    resource: "@NetworkingElasticSearchBundle/Resources/config/routing.yml"
#    prefix:   /