security:
  firewalls:
    # -> custom firewall for the admin area of the URL
    admin:
      logout_on_user_change: true
      switch_user:        true
      context:            user
      pattern:            /admin(.*)
      form_login:
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
        login_path:     /admin/login
        use_forward:    false
        check_path:     /admin/login_check
        failure_path:   null
        use_referer:    true
        default_target_path: /admin/dashboard
      logout:
        path:           /admin/logout
        target:         /
        invalidate_session: true
        delete_cookies:
          PHPSESSID: ~

